name: CI

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

env:
  MIX_ENV: dev

jobs:
  deps:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1.5.0
        with:
          elixir-version: 1.12.3
          otp-version: 24.0
          experimental-otp: true
          

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-24.0-1.12.3-${{ hashFiles('mix.lock') }}
        
      - name: Add inotify
        run: sudo apt-get install -y inotify-tools 

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix compile
          mix ecto.create
          mix ecto.migrate
          mix dialyzer --plt

  credo:
    name: Credo
    needs: deps
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1.5.0
        with:
          elixir-version: 1.12.3
          otp-version: 24.0
          experimental-otp: true
      
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-24.0-1.12.3-${{ hashFiles('mix.lock') }}

      - name: Run Credo
        run: mix credo --strict

  dialyzer:
    name: Dialyzer
    needs: deps
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1.5.0
        with:
          elixir-version: 1.12.3
          otp-version: 24.0
          experimental-otp: true

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-24.0-1.12.3-${{ hashFiles('mix.lock') }}

      - name: Run Dialyzer
        run: mix dialyzer

  unit_tests:
    env:
      MIX_ENV: test
      
    name: Tests
    needs: deps
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1.5.0
        with:
          elixir-version: 1.12.3
          otp-version: 24.0
          experimental-otp: true

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-24.0-1.12.3-${{ hashFiles('mix.lock') }}

      - name: Check Code Format
        run: mix format --check-formatted

      - name: Run test
        run: mix test
  
  deploy:
      needs: [unit_tests, dialyzer, credo]
      name: Deploy app
      runs-on: ubuntu-latest
      env: 
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"
